### ISSUE TITLE
Get User , Unauthorized 

### ISSUE THREAD

**Issue by Rashmi-278** [Rashmi-278/fauna-adapter-test#2]
After submitting the email . error with email signin

Console log error
```

event - compiled successfully
fauna_getUserByEmail zckvlhxjbcgzjtzhyx@miucce.com
GET_USER_BY_EMAIL [Unauthorized: unauthorized] {
  description: 'Unauthorized',
  requestResult: RequestResult {
    method: 'POST',
    path: '',
    query: null,
    requestRaw: '{"let":[{"ref":{"match":{"index":"user_by_email"},"terms":"zckvlhxjbcgzjtzhyx@miucce.com"}}],"in":{"if":{"exists":{"var":"ref"}},"then":{"get":{"var":"ref"}},"else":null}}',
    requestContent: Expr { raw: [Object] },
    responseRaw: '{"errors":[{"code":"unauthorized","description":"Unauthorized"}]}',
    responseContent: { errors: [Array] },
    statusCode: 401,
    responseHeaders: [Object: null prototype] {
      ':status': 401,
      'www-authenticate': 'Basic realm="Unauthorized"',
      'x-txn-time': '1614005141061643',
      'x-faunadb-build': '21.02.02.rc9-fc00d62',
      'content-length': '65',
      'content-type': 'application/json;charset=utf-8'
    },
    startTime: 1614005140451,
    endTime: 1614005141318
  }
}
(node:12203) UnhandledPromiseRejectionWarning: Error: GET_USER_BY_EMAIL
    at getUserByEmail (webpack-internal:///./utils/fauna.js:98:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12203) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:12203) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Rashmi-278** [comment]
Make sure the names of Indexes and Collections in Your DB are same as in adapter.

collections = {
      User: 'user',
      Account: 'account',
      Session: 'session',
      VerificationRequest: 'verification_request'
    },
    indexes = {
      Account: 'account_by_provider_account_id',
      User: 'user_by_email',
      Session: 'session_by_token',
      VerificationRequest: 'verification_request_by_token'
    }
